"""domain_2_watch_sessions

Revision ID: 1ca9d0cbff05
Revises: c629964e0aa9
Create Date: 2026-04-22 16:26:55.711648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ca9d0cbff05'
down_revision: Union[str, Sequence[str], None] = 'c629964e0aa9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('watch_sessions',
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('anilist_id', sa.Integer(), nullable=False),
    sa.Column('episode_number', sa.Float(), nullable=False),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('watch_duration_sec', sa.Integer(), nullable=True),
    sa.Column('total_duration_sec', sa.Integer(), nullable=True),
    sa.Column('completion_rate', sa.Float(), nullable=True),
    sa.Column('drop_timestamp_sec', sa.Integer(), nullable=True),
    sa.Column('quality_watched', sa.String(), nullable=True),
    sa.Column('provider_used', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['anilist_id'], ['anime_metadata.anilistId'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index('idx_watch_sessions_anime', 'watch_sessions', ['anilist_id', 'episode_number'], unique=False)
    op.create_index('idx_watch_sessions_user', 'watch_sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_watch_sessions_user', table_name='watch_sessions')
    op.drop_index('idx_watch_sessions_anime', table_name='watch_sessions')
    op.drop_table('watch_sessions')
    # ### end Alembic commands ###
