"""drop_legacy_watch_events

Revision ID: cd9364ff331d
Revises: 1ca9d0cbff05
Create Date: 2026-04-22 16:36:10.939189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cd9364ff331d'
down_revision: Union[str, Sequence[str], None] = '1ca9d0cbff05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_watch_events_episode'), table_name='watch_events')
    op.drop_table('watch_events')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('watch_events',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('anilistId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('episodeNumber', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('event_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('timestamp_sec', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('watch_events_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('watch_events_pkey'))
    )
    op.create_index(op.f('idx_watch_events_episode'), 'watch_events', ['anilistId', 'episodeNumber'], unique=False)
    # ### end Alembic commands ###
