"""domain_1_canonical_metadata

Revision ID: dd60be6dc1b6
Revises: ad17d0f5a71a
Create Date: 2026-04-22 16:09:15.865508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dd60be6dc1b6'
down_revision: Union[str, Sequence[str], None] = 'ad17d0f5a71a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('canonical_anime',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('anilist_id', sa.Integer(), nullable=False),
    sa.Column('mal_id', sa.Integer(), nullable=True),
    sa.Column('kitsu_id', sa.Integer(), nullable=True),
    sa.Column('title_preferred', sa.Text(), nullable=False),
    sa.Column('episode_count_actual', sa.Integer(), nullable=True),
    sa.Column('air_schedule_wib', sa.Text(), nullable=True),
    sa.Column('genres_local', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('last_reconciled_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['anilist_id'], ['anime_metadata.anilistId'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('anilist_id')
    )
    op.create_table('metadata_sources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('canonical_id', sa.Integer(), nullable=False),
    sa.Column('source_name', sa.String(), nullable=False),
    sa.Column('field_name', sa.String(), nullable=False),
    sa.Column('raw_value', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['canonical_id'], ['canonical_anime.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_metadata_sources_canonical', 'metadata_sources', ['canonical_id', 'source_name', 'field_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_metadata_sources_canonical', table_name='metadata_sources')
    op.drop_table('metadata_sources')
    op.drop_table('canonical_anime')
    # ### end Alembic commands ###
